# -*- coding: utf-8 -*-
"""unemployed.csv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HmWKKo9JuS_XS7mLnAKiyXtOtPwPf8B

Import libraries
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

"""Load dataset"""

df = pd.read_csv("/content/Unemployment in India.csv")

df.head()

df.tail()

df.shape

df.info()

df.columns = df.columns.str.strip()

df.isnull().sum()

df.dropna(inplace=True)

df.isnull().sum()

df['Area'].unique()

df['Region'].unique()

df['Frequency'].unique()

df['Date'].unique()

df['Date'] = pd.to_datetime(df['Date'])

df['Estimated Unemployment Rate (%)'].mean()

df.groupby('Region')['Estimated Unemployment Rate (%)'].mean()

df.groupby('Region')['Estimated Unemployment Rate (%)'].mean().sort_values(ascending=False)

plt.figure(figsize=(12,6))

plt.plot(
    df['Date'],
    df['Estimated Unemployment Rate (%)']
)

plt.xticks(rotation=45)

plt.title("Unemployment Rate Over Time")

plt.show()

plt.figure(figsize=(12,6))

sns.barplot(
    x='Region',
    y='Estimated Unemployment Rate (%)',
    data=df
)

plt.xticks(rotation=90)

plt.show()

sns.boxplot(
    x='Area',
    y='Estimated Unemployment Rate (%)',
    data=df
)

plt.show()

covid = df[df['Date'] >= '2020-03-01']